"""Update ModelRegion to store filenames for bad images

Revision ID: 3a14f7e1719b
Revises: 5885024a7628
Create Date: 2024-10-21 10:16:50.187002

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3a14f7e1719b'
down_revision = '5885024a7628'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_region', sa.Column('bad_image_1_filename', sa.String(length=256), nullable=True))
    op.add_column('model_region', sa.Column('bad_image_2_filename', sa.String(length=256), nullable=True))
    op.add_column('model_region', sa.Column('bad_image_3_filename', sa.String(length=256), nullable=True))
    op.add_column('model_region', sa.Column('bad_image_4_filename', sa.String(length=256), nullable=True))
    op.add_column('model_region', sa.Column('bad_image_5_filename', sa.String(length=256), nullable=True))
    op.add_column('model_region', sa.Column('bad_image_1_aligned_filename', sa.String(length=256), nullable=True))
    op.add_column('model_region', sa.Column('bad_image_2_aligned_filename', sa.String(length=256), nullable=True))
    op.add_column('model_region', sa.Column('bad_image_3_aligned_filename', sa.String(length=256), nullable=True))
    op.add_column('model_region', sa.Column('bad_image_4_aligned_filename', sa.String(length=256), nullable=True))
    op.add_column('model_region', sa.Column('bad_image_5_aligned_filename', sa.String(length=256), nullable=True))
    op.drop_column('model_region', 'bad_image_3_url')
    op.drop_column('model_region', 'bad_image_4_url')
    op.drop_column('model_region', 'bad_image_4_aligned_url')
    op.drop_column('model_region', 'bad_image_5_aligned_url')
    op.drop_column('model_region', 'bad_image_1_aligned_url')
    op.drop_column('model_region', 'bad_image_2_aligned_url')
    op.drop_column('model_region', 'bad_image_1_url')
    op.drop_column('model_region', 'bad_image_3_aligned_url')
    op.drop_column('model_region', 'bad_image_2_url')
    op.drop_column('model_region', 'bad_image_5_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_region', sa.Column('bad_image_5_url', mysql.VARCHAR(length=256), nullable=True))
    op.add_column('model_region', sa.Column('bad_image_2_url', mysql.VARCHAR(length=256), nullable=True))
    op.add_column('model_region', sa.Column('bad_image_3_aligned_url', mysql.VARCHAR(length=256), nullable=True))
    op.add_column('model_region', sa.Column('bad_image_1_url', mysql.VARCHAR(length=256), nullable=True))
    op.add_column('model_region', sa.Column('bad_image_2_aligned_url', mysql.VARCHAR(length=256), nullable=True))
    op.add_column('model_region', sa.Column('bad_image_1_aligned_url', mysql.VARCHAR(length=256), nullable=True))
    op.add_column('model_region', sa.Column('bad_image_5_aligned_url', mysql.VARCHAR(length=256), nullable=True))
    op.add_column('model_region', sa.Column('bad_image_4_aligned_url', mysql.VARCHAR(length=256), nullable=True))
    op.add_column('model_region', sa.Column('bad_image_4_url', mysql.VARCHAR(length=256), nullable=True))
    op.add_column('model_region', sa.Column('bad_image_3_url', mysql.VARCHAR(length=256), nullable=True))
    op.drop_column('model_region', 'bad_image_5_aligned_filename')
    op.drop_column('model_region', 'bad_image_4_aligned_filename')
    op.drop_column('model_region', 'bad_image_3_aligned_filename')
    op.drop_column('model_region', 'bad_image_2_aligned_filename')
    op.drop_column('model_region', 'bad_image_1_aligned_filename')
    op.drop_column('model_region', 'bad_image_5_filename')
    op.drop_column('model_region', 'bad_image_4_filename')
    op.drop_column('model_region', 'bad_image_3_filename')
    op.drop_column('model_region', 'bad_image_2_filename')
    op.drop_column('model_region', 'bad_image_1_filename')
    # ### end Alembic commands ###
