"""add name

Revision ID: 54ed690ce0ec
Revises: 2642898980ce
Create Date: 2024-10-17 12:54:10.462700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54ed690ce0ec'
down_revision = '2642898980ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_region', sa.Column('name', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_region', 'name')
    # ### end Alembic commands ###
