"""Add pass and fail descriptions to ModelRegion

Revision ID: 55ccc9ad8905
Revises: 54ed690ce0ec
Create Date: 2024-10-18 11:03:18.473337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55ccc9ad8905'
down_revision = '54ed690ce0ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_region', sa.Column('pass_description', sa.Text(), nullable=True))
    op.add_column('model_region', sa.Column('fail_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_region', 'fail_description')
    op.drop_column('model_region', 'pass_description')
    # ### end Alembic commands ###
