"""Add aligned images

Revision ID: 5872ac9b0257
Revises: 55ccc9ad8905
Create Date: 2024-10-18 11:39:00.913637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5872ac9b0257'
down_revision = '55ccc9ad8905'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model', sa.Column('aligned_good_image_1_url', sa.String(length=256), nullable=True))
    op.add_column('model', sa.Column('aligned_good_image_2_url', sa.String(length=256), nullable=True))
    op.add_column('model', sa.Column('aligned_good_image_3_url', sa.String(length=256), nullable=True))
    op.add_column('model', sa.Column('aligned_good_image_4_url', sa.String(length=256), nullable=True))
    op.add_column('model', sa.Column('aligned_good_image_5_url', sa.String(length=256), nullable=True))
    op.add_column('model_region', sa.Column('aligned_bad_image_1_url', sa.String(length=256), nullable=True))
    op.add_column('model_region', sa.Column('aligned_bad_image_2_url', sa.String(length=256), nullable=True))
    op.add_column('model_region', sa.Column('aligned_bad_image_3_url', sa.String(length=256), nullable=True))
    op.add_column('model_region', sa.Column('aligned_bad_image_4_url', sa.String(length=256), nullable=True))
    op.add_column('model_region', sa.Column('aligned_bad_image_5_url', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_region', 'aligned_bad_image_5_url')
    op.drop_column('model_region', 'aligned_bad_image_4_url')
    op.drop_column('model_region', 'aligned_bad_image_3_url')
    op.drop_column('model_region', 'aligned_bad_image_2_url')
    op.drop_column('model_region', 'aligned_bad_image_1_url')
    op.drop_column('model', 'aligned_good_image_5_url')
    op.drop_column('model', 'aligned_good_image_4_url')
    op.drop_column('model', 'aligned_good_image_3_url')
    op.drop_column('model', 'aligned_good_image_2_url')
    op.drop_column('model', 'aligned_good_image_1_url')
    # ### end Alembic commands ###
