"""update

Revision ID: 94493853f28b
Revises: c39d2d10c246
Create Date: 2024-10-21 12:18:38.563077

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '94493853f28b'
down_revision = 'c39d2d10c246'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model', 'fail_description')
    op.drop_column('model', 'pass_description')
    op.add_column('model_region', sa.Column('fail_description', sa.Text(), nullable=True))
    op.add_column('model_region', sa.Column('pass_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_region', 'pass_description')
    op.drop_column('model_region', 'fail_description')
    op.add_column('model', sa.Column('pass_description', mysql.TEXT(), nullable=True))
    op.add_column('model', sa.Column('fail_description', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
