"""add descriptions


Revision ID: c39d2d10c246
Revises: 3a14f7e1719b
Create Date: 2024-10-21 11:46:29.274293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c39d2d10c246'
down_revision = '3a14f7e1719b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model', sa.Column('fail_description', sa.Text(), nullable=True))
    op.add_column('model', sa.Column('pass_description', sa.Text(), nullable=True))
    op.add_column('model_region', sa.Column('model_pkl', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_region', 'model_pkl')
    op.drop_column('model', 'pass_description')
    op.drop_column('model', 'fail_description')
    # ### end Alembic commands ###
